# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_oper',
            name='oper',
            field=models.CharField(blank=True, max_length=150, verbose_name='Операция'),
        ),
    ]
