# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_checklist', '0002_auto_20180808_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implant_detail',
            name='implant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_checklist.s_implant', verbose_name='Импланты и протезы'),
        ),
    ]
