# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_checklist', '0003_auto_20180808_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='tbs',
            field=models.BooleanField(default=False, verbose_name='TBS'),
        ),
    ]
